import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Orbitron } from "next/font/google";
import "./globals.css";
import GlassyNavbar from "@/components/navbar/Navbar";

import CinematicFooter from "@/components/Footer";
import LenisProvider from "@/providers/LenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-orbitron",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"], // pick what you need
  display: "swap",
  variable: "--font-manrope", // exposes as CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${manrope.variable} antialiased`}
      >
        <LenisProvider>
          <GlassyNavbar />
          {children}
          <CinematicFooter />
        </LenisProvider>
      </body>
    </html>
  );
}
